# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: stelloauth

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: stelloauth
    main: .
    binary: stelloauth
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

dockers:
  - id: docker-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/tamcore/stelloauth:{{ .Version }}-amd64"
      - "ghcr.io/tamcore/stelloauth:latest-amd64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: docker-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/tamcore/stelloauth:{{ .Version }}-arm64"
      - "ghcr.io/tamcore/stelloauth:latest-arm64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/tamcore/stelloauth:{{ .Version }}"
    image_templates:
      - "ghcr.io/tamcore/stelloauth:{{ .Version }}-amd64"
      - "ghcr.io/tamcore/stelloauth:{{ .Version }}-arm64"
  - name_template: "ghcr.io/tamcore/stelloauth:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/tamcore/stelloauth:{{ .Version }}-amd64"
      - "ghcr.io/tamcore/stelloauth:{{ .Version }}-arm64"
  - name_template: "ghcr.io/tamcore/stelloauth:latest"
    image_templates:
      - "ghcr.io/tamcore/stelloauth:{{ .Version }}-amd64"
      - "ghcr.io/tamcore/stelloauth:{{ .Version }}-arm64"
