{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stelloauth.fullname" . }}-metrics
  labels:
    {{- include "stelloauth.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "stelloauth.selectorLabels" . | nindent 4 }}
{{- end }}
